version: 2

restore_cache: &restore_cache
  restore_cache:
    keys:
      - jars-{{ checksum "build.gradle" }}
      - builds-{{ .Revision }}
jobs:
  test:
    working_directory: ~/circieci
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Test
          command: |
            ./gradlew test
            ./gradlew jacocoTestReport
      - run:
          name: Report coverage
          command: bash <(curl -s https://codecov.io/bash) -t d295dceb-ac5c-4cde-94b4-21d58516cd74
      - save_cache:
          paths:
            - ~/circleci/build
          key: builds-{{ .Revision }}

workflows:
  version: 2
  test:
    jobs:
      - test
