package com.github.unhappychoice.circleci.response

import java.util.*

data class Build(
  val allCommitDetails: List<Commit>?,
  val authorEmail: String?,
  val authorDate: String?,
  val authorName: String?,
  val body: String?,
  val branch: String?,
  val buildNum: Int?,
  val buildTimeMillis: Int?,
  val buildUrl: String?,
  val canceled: Boolean?,
  val canceler: User?,
  val circleYml: Map<String, Any>?,
  val committerEmail: String?,
  val committerDate: String?,
  val committerName: String?,
  val compare: String?,
  val dontBuild: Boolean?,
  val failed: Boolean?,
  val infrastructureFail: Boolean?,
  val isFirstGreenBuild: Boolean?,
  val jobName: String?,
  val lifecycle: String?,
  val outcome: String?,
  val previous: Map<String, Any>?,
  val queuedAt: Date?,
  val retries: List<Int>?,
  val retryOf: Int?,
  val reponame: String?,
  val startTime: Date?,
  val status: String?,
  val steps: List<BuildStep>?,
  val stopTime: Date?,
  val subject: String?,
  val timedout: Boolean?,
  val usageQueuedAt: Date?,
  val user: Map<String, Any>?,
  val username: String?,
  val vcsRevision: String?,
  val vcsTag: String?,
  val vcsUrl: String?,
  val why: String?,
  val workflows: Workflow?
)
